### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by potapovDim** [Gennadiii/tests-selector#3]
Stack: Can't start tests: TypeError: Cannot read property 'value' of undefined
(node:13992) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined,
**error from select-prompt/index.js:112:31**

env: 
OS                     - mac os
node                  - v14.5.0
tests-selector   - 1.1.3

const SpecsSelector = require('tests-selector').default

console.log(require('fs').existsSync(`${process.cwd()}/built/specs/`)) // true
console.log(require('fs').existsSync(`${process.cwd()}/built/specs/base.spec.js`)) // true
console.log(require('fs').existsSync(`${process.cwd()}/built/specs/base1.spec.js`)) // true

if(require.main === module) {
  void async function() {
    const specsSelector = new SpecsSelector({
      specsPath: `${process.cwd()}/built/specs/`,
      specIdentifiers: ['spec'],
    });
    await specsSelector.selectTests();
  }();
}

**Comment by Gennadiii** [comment]
I'll add something to handle this. Single level nesting is not supported. This tool is needed when you have a lot of tests. But the error is not good, thanks

**Comment by potapovDim** [comment]
@Gennadiii hm, it is not good, i think, i can have many spec files in one dir, this approach restricts library usage

**Comment by Gennadiii** [comment]
@potapovDim It's fine to have many in one. Only non is not supported. If you have 3 specs in your specs folder you probably don't need this lib. If you have 100 tests in the same folder this lib won't be useful. If you have subfolders in spec folder filled with tests and other subfolders that's when this solution becomes handy.

**Comment by potapovDim** [comment]
@Gennadiii it's a pity 😔 also it can affect usability of the library, for example i try this lib on my pet project with few tests in one spec folder - it fails - i think that library is broken and i don`t want to use it on real project

**Comment by Gennadiii** [comment]
I'll either add support of it or error message

**Comment by potapovDim** [comment]
@Gennadiii ⬆

**Comment by Gennadiii** [comment]
@potapovDim fixed in 1.1.6 (such cases are now supported)
